//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SACH()
        {
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
            this.CTPNs = new HashSet<CTPN>();
        }
    
        public string MASACH { get; set; }
        public string TENSACH { get; set; }
        public string MATG { get; set; }
        public string MALOAI { get; set; }
        public string MANXB { get; set; }
        public Nullable<int> GIA { get; set; }
        public Nullable<int> SOLUONG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPN> CTPNs { get; set; }
        public virtual NHAXUATBAN NHAXUATBAN { get; set; }
        public virtual NHAXUATBAN NHAXUATBAN1 { get; set; }
        public virtual TACGIA TACGIA { get; set; }
        public virtual THELOAI THELOAI { get; set; }
        public virtual THELOAI THELOAI1 { get; set; }
        public virtual TACGIA TACGIA1 { get; set; }
    }
}
